import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useNotifications, useMarkNotificationsRead, useMarkNotificationSingleRead } from '../hooks/useNotifications'
import SidebarLayout from '../components/SidebarLayout'
import { 
  Bell, 
  CheckCheck, 
  Loader2, 
  AlertTriangle,
  AlertOctagon,
  CalendarDays,
  FileCheck,
  Package,
  CreditCard
} from 'lucide-react'

const NotificationsPage: React.FC = () => {
  const navigate = useNavigate()
  const { data, isLoading } = useNotifications()
  const markAllReadMutation = useMarkNotificationsRead()
  const markSingleReadMutation = useMarkNotificationSingleRead()

  const [filter, setFilter] = useState<'all' | 'unread' | 'alerts'>('all')

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString()
  }

  const getAlertIcon = (type: string) => {
    switch (type) {
      case 'BUDGET_EXCEEDED':
        return <AlertOctagon className="h-5 w-5 text-rose-400" />
      case 'BUDGET_WARNING':
        return <AlertTriangle className="h-5 w-5 text-yellow-400" />
      case 'TASK_OVERDUE':
        return <CalendarDays className="h-5 w-5 text-orange-400" />
      case 'LOW_STOCK':
        return <Package className="h-5 w-5 text-blue-400" />
      case 'MILESTONE_COMPLETED':
        return <FileCheck className="h-5 w-5 text-emerald-400" />
      case 'PAYMENT_DUE':
        return <CreditCard className="h-5 w-5 text-cyan-400" />
      default:
        return <Bell className="h-5 w-5 text-zinc-400" />
    }
  }

  const handleNotificationClick = (item: any) => {
    // Mark as read first
    if (!item.read) {
      markSingleReadMutation.mutate(item.id)
    }

    // Navigate to relevant pages based on type
    if (item.type.includes('BUDGET')) {
      navigate('/budget')
    } else if (item.type.includes('TASK')) {
      navigate('/projects')
    } else if (item.type.includes('STOCK') || item.type.includes('LOW')) {
      navigate('/materials')
    } else if (item.type.includes('MILESTONE')) {
      navigate('/projects')
    } else if (item.type.includes('PAYMENT')) {
      navigate('/payments')
    }
  }

  const handleMarkAllRead = () => {
    markAllReadMutation.mutate()
  }

  const notifications = data?.notifications || []
  
  // Filter notifications
  const filteredNotifications = notifications.filter((n: any) => {
    if (filter === 'unread') return !n.read
    if (filter === 'alerts') return n.type.includes('EXCEEDED') || n.type.includes('WARNING') || n.type.includes('OVERDUE')
    return true
  })

  return (
    <SidebarLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="border-b border-zinc-800 pb-5 flex flex-col sm:flex-row justify-between sm:items-center gap-4">
          <div>
            <h1 className="text-3xl font-black text-white flex items-center">
              <Bell className="h-7 w-7 mr-2 text-violet-500" /> System Notifications
            </h1>
            <p className="text-zinc-400 text-xs mt-1">
              Audit automated alerts generated by stock levels, budget caps, payment milestones, and delays.
            </p>
          </div>
          
          <button
            onClick={handleMarkAllRead}
            disabled={markAllReadMutation.isPending || notifications.filter((n: any) => !n.read).length === 0}
            className="inline-flex items-center px-4 py-2 bg-zinc-950 hover:bg-zinc-850 border border-zinc-800 hover:border-zinc-700 text-zinc-300 hover:text-white rounded-lg text-xs font-bold uppercase tracking-wider transition-all disabled:opacity-40"
          >
            <CheckCheck className="h-4 w-4 mr-2" /> Mark All as Read
          </button>
        </div>

        {/* Filter selection */}
        <div className="flex space-x-1.5 bg-[#14161f] border border-zinc-800 p-1 rounded-lg w-fit">
          <button
            onClick={() => setFilter('all')}
            className={`px-4 py-2 rounded-md text-xs font-bold uppercase tracking-wider transition-all cursor-pointer ${
              filter === 'all' ? 'bg-violet-650 text-white' : 'text-zinc-400 hover:text-white hover:bg-zinc-800/40'
            }`}
          >
            All Messages ({notifications.length})
          </button>
          <button
            onClick={() => setFilter('unread')}
            className={`px-4 py-2 rounded-md text-xs font-bold uppercase tracking-wider transition-all cursor-pointer ${
              filter === 'unread' ? 'bg-violet-650 text-white' : 'text-zinc-400 hover:text-white hover:bg-zinc-800/40'
            }`}
          >
            Unread ({data?.unreadCount || 0})
          </button>
          <button
            onClick={() => setFilter('alerts')}
            className={`px-4 py-2 rounded-md text-xs font-bold uppercase tracking-wider transition-all cursor-pointer ${
              filter === 'alerts' ? 'bg-violet-650 text-white' : 'text-zinc-400 hover:text-white hover:bg-zinc-800/40'
            }`}
          >
            Alerts
          </button>
        </div>

        {/* Notifications Grid */}
        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-20 bg-[#14161f] border border-zinc-800 rounded-xl shadow-xl">
            <Loader2 className="h-8 w-8 text-violet-500 animate-spin" />
            <p className="text-xs text-zinc-400 font-medium mt-3">Synthesizing inbox...</p>
          </div>
        ) : (
          <div className="bg-[#14161f] border border-zinc-800 rounded-xl overflow-hidden shadow-xl max-w-3xl">
            <div className="divide-y divide-zinc-850">
              {filteredNotifications.map((item: any) => (
                <div
                  key={item.id}
                  onClick={() => handleNotificationClick(item)}
                  className={`p-4 flex items-start space-x-4 cursor-pointer transition-all ${
                    item.read 
                      ? 'bg-transparent hover:bg-zinc-950/20' 
                      : 'bg-violet-600/5 hover:bg-violet-600/10 border-l-2 border-violet-500'
                  }`}
                >
                  <div className="p-2 rounded bg-zinc-950 border border-zinc-850 shrink-0">
                    {getAlertIcon(item.type)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex justify-between items-start gap-4">
                      <p className={`text-xs font-semibold leading-normal ${item.read ? 'text-zinc-300' : 'text-white font-bold'}`}>
                        {item.message}
                      </p>
                      {!item.read && (
                        <span className="w-2 h-2 rounded-full bg-violet-550 shrink-0 mt-1.5" title="New alert"></span>
                      )}
                    </div>
                    <span className="block text-[9px] text-zinc-550 font-bold uppercase tracking-wider mt-1.5">
                      {formatDate(item.createdAt)}
                    </span>
                  </div>
                </div>
              ))}
              {filteredNotifications.length === 0 && (
                <div className="p-16 text-center text-zinc-550 text-xs font-semibold">
                  No notifications found matching the filter.
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </SidebarLayout>
  )
}

export default NotificationsPage
