import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useNotifications, useMarkNotificationsRead, useMarkNotificationSingleRead } from '../hooks/useNotifications'
import SidebarLayout from '../components/SidebarLayout'
import { 
  Bell, 
  CheckCheck, 
  Loader2, 
  AlertTriangle,
  AlertOctagon,
  CalendarDays,
  FileCheck,
  Package,
  CreditCard,
  ArrowLeft
} from 'lucide-react'

const NotificationsPage: React.FC = () => {
  const navigate = useNavigate()
  const { data, isLoading } = useNotifications()
  const markAllReadMutation = useMarkNotificationsRead()
  const markSingleReadMutation = useMarkNotificationSingleRead()

  const [filter, setFilter] = useState<'all' | 'unread' | 'alerts'>('all')

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString()
  }

  const getAlertIcon = (type: string) => {
    switch (type) {
      case 'BUDGET_EXCEEDED':
        return <AlertOctagon className="h-5 w-5 text-rose-455" />
      case 'BUDGET_WARNING':
        return <AlertTriangle className="h-5 w-5 text-amber-400" />
      case 'TASK_OVERDUE':
        return <CalendarDays className="h-5 w-5 text-orange-400" />
      case 'LOW_STOCK':
        return <Package className="h-5 w-5 text-[#7c3aed]" />
      case 'MILESTONE_COMPLETED':
        return <FileCheck className="h-5 w-5 text-emerald-400" />
      case 'PAYMENT_DUE':
        return <CreditCard className="h-5 w-5 text-[#00d2ff]" />
      default:
        return <Bell className="h-5 w-5 text-slate-400" />
    }
  }

  const handleNotificationClick = (item: any) => {
    // Mark as read first
    if (!item.read) {
      markSingleReadMutation.mutate(item.id)
    }

    // Navigate to relevant pages based on type
    if (item.type.includes('BUDGET')) {
      navigate('/budget')
    } else if (item.type.includes('TASK')) {
      navigate('/projects')
    } else if (item.type.includes('STOCK') || item.type.includes('LOW')) {
      navigate('/materials')
    } else if (item.type.includes('MILESTONE')) {
      navigate('/projects')
    } else if (item.type.includes('PAYMENT')) {
      navigate('/payments')
    }
  }

  const handleMarkAllRead = () => {
    markAllReadMutation.mutate()
  }

  const notifications = data?.notifications || []
  
  // Filter notifications
  const filteredNotifications = notifications.filter((n: any) => {
    if (filter === 'unread') return !n.read
    if (filter === 'alerts') return n.type.includes('EXCEEDED') || n.type.includes('WARNING') || n.type.includes('OVERDUE')
    return true
  })

  return (
    <SidebarLayout>
      <div className="space-y-6">
        {/* Breadcrumb Header */}
        <div className="border-b border-white/10 pb-5">
          <Link to="/settings" className="inline-flex items-center text-xs font-bold text-slate-400 hover:text-white uppercase tracking-widest mb-3 cursor-pointer">
            <ArrowLeft className="h-4 w-4 mr-1.5" /> Back to Settings
          </Link>
          <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4 mt-2">
            <div>
              <h1 className="text-3xl font-black text-white flex items-center tracking-tight">
                <Bell className="h-7 w-7 mr-2 text-[#7c3aed]" /> System Notifications
              </h1>
              <p className="text-slate-400 text-xs font-semibold mt-1">
                Audit automated alerts generated by stock levels, budget caps, payment milestones, and delays.
              </p>
            </div>
            
            <button
              onClick={handleMarkAllRead}
              disabled={markAllReadMutation.isPending || notifications.filter((n: any) => !n.read).length === 0}
              className="inline-flex items-center px-4 py-2 bg-[#0a0f1d]/60 hover:bg-white/[0.04] text-[#00d2ff] border border-white/10 rounded-xl text-xs font-bold uppercase tracking-widest transition-all disabled:opacity-40 cursor-pointer"
            >
              <CheckCheck className="h-4 w-4 mr-2" /> Mark All as Read
            </button>
          </div>
        </div>

        {/* Filter selection */}
        <div className="flex space-x-1.5 bg-[#0d1322]/70 border border-white/10 p-1 rounded-2xl w-fit backdrop-blur-xl">
          <button
            onClick={() => setFilter('all')}
            className={`px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all cursor-pointer ${
              filter === 'all' ? 'bg-[#7c3aed] text-white' : 'text-slate-400 hover:text-white hover:bg-white/[0.04]'
            }`}
          >
            All Messages ({notifications.length})
          </button>
          <button
            onClick={() => setFilter('unread')}
            className={`px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all cursor-pointer ${
              filter === 'unread' ? 'bg-[#7c3aed] text-white' : 'text-slate-400 hover:text-white hover:bg-white/[0.04]'
            }`}
          >
            Unread ({data?.unreadCount || 0})
          </button>
          <button
            onClick={() => setFilter('alerts')}
            className={`px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all cursor-pointer ${
              filter === 'alerts' ? 'bg-[#7c3aed] text-white' : 'text-slate-400 hover:text-white hover:bg-white/[0.04]'
            }`}
          >
            Alerts
          </button>
        </div>

        {/* Notifications Grid */}
        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-20 bg-[#0d1322]/70 border border-white/10 rounded-2xl shadow-xl backdrop-blur-xl relative max-w-3xl">
            <div className="absolute top-0 left-0 right-0 h-[3px] bg-gradient-to-r from-[#7c3aed] via-[#00d2ff] to-transparent" />
            <Loader2 className="h-8 w-8 text-[#7c3aed] animate-spin" />
            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest mt-3">Synthesizing inbox...</p>
          </div>
        ) : (
          <div className="bg-[#0d1322]/70 border border-white/10 rounded-2xl overflow-hidden shadow-xl max-w-3xl backdrop-blur-xl relative">
            <div className="absolute top-0 left-0 right-0 h-[3px] bg-gradient-to-r from-[#7c3aed] via-[#00d2ff] to-transparent" />
            <div className="divide-y divide-white/10">
              {filteredNotifications.map((item: any) => (
                <div
                  key={item.id}
                  onClick={() => handleNotificationClick(item)}
                  className={`p-4 flex items-start space-x-4 cursor-pointer transition-all ${
                    item.read 
                      ? 'bg-transparent hover:bg-white/[0.015]' 
                      : 'bg-[#7c3aed]/5 hover:bg-[#7c3aed]/10 border-l-[3px] border-[#7c3aed]'
                  }`}
                >
                  <div className="p-2 rounded-xl bg-[#0a0f1d]/60 border border-white/10 shrink-0">
                    {getAlertIcon(item.type)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex justify-between items-start gap-4">
                      <p className={`text-xs font-semibold leading-normal ${item.read ? 'text-slate-300' : 'text-white font-bold'}`}>
                        {item.message}
                      </p>
                      {!item.read && (
                        <span className="w-2.5 h-2.5 rounded-full bg-[#00d2ff] shrink-0 mt-1.5 shadow-lg shadow-[#00d2ff]/40" title="New alert"></span>
                      )}
                    </div>
                    <span className="block text-[10px] text-slate-500 font-bold uppercase tracking-widest mt-1.5">
                      {formatDate(item.createdAt)}
                    </span>
                  </div>
                </div>
              ))}
              {filteredNotifications.length === 0 && (
                <div className="p-16 text-center text-slate-500 font-bold uppercase tracking-widest bg-[#0d1322]/70">
                  No notifications found matching the filter.
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </SidebarLayout>
  )
}

export default NotificationsPage
